name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-release
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release-package:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Add git author
        run: |
          git config --global user.email "***"
          git config --global user.name "***"

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:esm

      - name: Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
