name: Test

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-tests
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build and test size
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target' || github.event_name == 'push'
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: "ci"
          pattern: "./dist/*.{js,css}"
          compression: "none"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Lint TS
        run: yarn lint:ts

      - name: Lint SCSS
        run: yarn lint:css

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
